import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const cabinetGrotesk = localFont({
  src: "./assets/fonts/CabinetGrotesk-Regular.otf",
  variable: "--font-cabinet-grotesk",
  display: "swap",
});
const bricolage = localFont({
  src: "./assets/fonts/BricolageGrotesque.ttf",
  variable: "--font-bricolage",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cabinetGrotesk.className} ${cabinetGrotesk.variable} ${bricolage.variable} antialiased bg-black`}
      >
        {children}
      </body>
    </html>
  );
}
