import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const cabinetGrotesk = localFont({
  src: '../app/assets/fonts/CabinetGrotesk-Regular.otf',
  variable:"--font-cabinetGrotesk",
  display: "swap",
})
const bricolage = localFont({
  src: '../app/assets/fonts/BricolageGrotesque.ttf',
  variable:"--font-bricolage",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cabinetGrotesk.variable}  ${bricolage.variable} antialiased bg-black `}
      >
        {children}
      </body>
    </html>
  );
}
